# Generated by Django 3.0.11 on 2021-05-10 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0185_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubEventReminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(db_index=True, default="s", max_length=3)),
                (
                    "subevent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="juvare_reminder",
                        to="pretixbase.SubEvent",
                    ),
                ),
            ],
        ),
    ]
